chore(deps): update build-lint-test (#94)
This PR contains the following updates:

| Package | Type | Update | Change | Pending |
|---|---|---|---|---|
| [prettier](https://prettier.io)
([source](https://redirect.github.com/prettier/prettier)) |
devDependencies | patch | [`3.8.1` ->
`3.8.2`](https://renovatebot.com/diffs/npm/prettier/3.8.1/3.8.2) |
`3.8.3` |
|
[typescript-eslint](https://typescript-eslint.io/packages/typescript-eslint)
([source](https://redirect.github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/typescript-eslint))
| devDependencies | patch | [`8.58.0` ->
`8.58.1`](https://renovatebot.com/diffs/npm/typescript-eslint/8.58.0/8.58.1)
| `8.59.0` (+1) |
| [vite](https://vite.dev)
([source](https://redirect.github.com/vitejs/vite/tree/HEAD/packages/vite))
| devDependencies | patch | [`8.0.5` ->
`8.0.8`](https://renovatebot.com/diffs/npm/vite/8.0.5/8.0.8) | `8.0.10`
(+1) |

---

> [!WARNING]
> Some dependencies could not be looked up. Check the Dependency
Dashboard for more information.

---

### Release Notes

<details>
<summary>prettier/prettier (prettier)</summary>

###
[`v3.8.2`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#382)

[Compare
Source](https://redirect.github.com/prettier/prettier/compare/3.8.1...3.8.2)


[diff](https://redirect.github.com/prettier/prettier/compare/3.8.1...3.8.2)

##### Angular: Support Angular v21.2
([#&#8203;18722](https://redirect.github.com/prettier/prettier/pull/18722),
[#&#8203;19034](https://redirect.github.com/prettier/prettier/pull/19034)
by [@&#8203;fisker](https://redirect.github.com/fisker))

Exhaustive typechecking with `@default never;`

<!-- prettier-ignore -->

```html
<!-- Input -->
@&#8203;switch (foo) {
  @&#8203;case (1) {}
  @&#8203;default never;
}

<!-- Prettier 3.8.1 -->
SyntaxError: Incomplete block "default never". If you meant to write the @&#8203; character, you should use the "&#&#8203;64;" HTML entity instead. (3:3)

<!-- Prettier 3.8.2 -->
@&#8203;switch (foo) {
  @&#8203;case (1) {}
  @&#8203;default never;
}
```

`arrow function` and `instanceof` expressions.

<!-- prettier-ignore -->

```html
<!-- Input -->
@&#8203;let fn = (a) =>        a?    1:2;

{{ fn ( a         instanceof b)}}

<!-- Prettier 3.8.1 -->
@&#8203;let fn = (a) =>        a?    1:2;

{{ fn ( a         instanceof b)}}

<!-- Prettier 3.8.2 -->
@&#8203;let fn = (a) => (a ? 1 : 2);

{{ fn(a instanceof b) }}
```

</details>

<details>
<summary>typescript-eslint/typescript-eslint
(typescript-eslint)</summary>

###
[`v8.58.1`](https://redirect.github.com/typescript-eslint/typescript-eslint/blob/HEAD/packages/typescript-eslint/CHANGELOG.md#8581-2026-04-08)

[Compare
Source](https://redirect.github.com/typescript-eslint/typescript-eslint/compare/v8.58.0...v8.58.1)

This was a version bump only for typescript-eslint to align it with
other projects, there were no code changes.

See [GitHub
Releases](https://redirect.github.com/typescript-eslint/typescript-eslint/releases/tag/v8.58.1)
for more information.

You can read about our [versioning
strategy](https://typescript-eslint.io/users/versioning) and
[releases](https://typescript-eslint.io/users/releases) on our website.

</details>

<details>
<summary>vitejs/vite (vite)</summary>

###
[`v8.0.8`](https://redirect.github.com/vitejs/vite/blob/HEAD/packages/vite/CHANGELOG.md#small-808-2026-04-09-small)

[Compare
Source](https://redirect.github.com/vitejs/vite/compare/v8.0.7...v8.0.8)

##### Features

- update rolldown to 1.0.0-rc.15
([#&#8203;22201](https://redirect.github.com/vitejs/vite/issues/22201))
([6baf587](https://redirect.github.com/vitejs/vite/commit/6baf587255936e91348cbe624caefd10e8c607ab))

##### Bug Fixes

- avoid `dns.getDefaultResultOrder` temporary
([#&#8203;22202](https://redirect.github.com/vitejs/vite/issues/22202))
([15f1c15](https://redirect.github.com/vitejs/vite/commit/15f1c15ac9be343ee4f317fd025c3d67f0c7bd53))
- **ssr:** class property keys hoisting matching imports
([#&#8203;22199](https://redirect.github.com/vitejs/vite/issues/22199))
([e137601](https://redirect.github.com/vitejs/vite/commit/e1376018cd516d6970534fce495e24f9ee683ce3))

###
[`v8.0.7`](https://redirect.github.com/vitejs/vite/blob/HEAD/packages/vite/CHANGELOG.md#small-807-2026-04-07-small)

[Compare
Source](https://redirect.github.com/vitejs/vite/compare/v8.0.6...v8.0.7)

##### Bug Fixes

- use sync dns.getDefaultResultOrder instead of dns.promises
([#&#8203;22185](https://redirect.github.com/vitejs/vite/issues/22185))
([5c05b04](https://redirect.github.com/vitejs/vite/commit/5c05b04db6f3f64af60ff6525eb5f04bc330fbb5))

###
[`v8.0.6`](https://redirect.github.com/vitejs/vite/blob/HEAD/packages/vite/CHANGELOG.md#small-806-2026-04-07-small)

[Compare
Source](https://redirect.github.com/vitejs/vite/compare/v8.0.5...v8.0.6)

##### Features

- update rolldown to 1.0.0-rc.13
([#&#8203;22097](https://redirect.github.com/vitejs/vite/issues/22097))
([51d3e48](https://redirect.github.com/vitejs/vite/commit/51d3e48980bf3e352d31ecde49d1aa56859918e0))

##### Bug Fixes

- **css:** avoid mutating sass error multiple times
([#&#8203;22115](https://redirect.github.com/vitejs/vite/issues/22115))
([d5081c2](https://redirect.github.com/vitejs/vite/commit/d5081c2f3e73f3fc06956d8cf5f2cf06463c2325))
- **optimize-deps:** hoist CJS interop assignment
([#&#8203;22156](https://redirect.github.com/vitejs/vite/issues/22156))
([17a8f9e](https://redirect.github.com/vitejs/vite/commit/17a8f9edfcd3b9344668120a84e3328aeada3c97))

##### Performance Improvements

- early return in `getLocalhostAddressIfDiffersFromDNS` when DNS order
is `verbatim`
([#&#8203;22151](https://redirect.github.com/vitejs/vite/issues/22151))
([56ec256](https://redirect.github.com/vitejs/vite/commit/56ec25613dba6cc71911f7af6e545ebcb77ec012))

##### Miscellaneous Chores

- **create-vite:** remove unnecessary DOM.Iterable
([#&#8203;22168](https://redirect.github.com/vitejs/vite/issues/22168))
([bdc53ab](https://redirect.github.com/vitejs/vite/commit/bdc53ab1e67f7e2e000112eeed9c85413ddb0e9e))
- replace remaining prettier script
([#&#8203;22179](https://redirect.github.com/vitejs/vite/issues/22179))
([af71fb2](https://redirect.github.com/vitejs/vite/commit/af71fb26dd15098b9523efc3d8ed04f27553174b))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "* * * * 1" in timezone Etc/UTC,
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config
help](https://redirect.github.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Renovate
Bot](https://redirect.github.com/renovatebot/renovate).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4xMDcuMCIsInVwZGF0ZWRJblZlciI6IjM5LjEwNy4wIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->

Co-authored-by: elastic-renovate-prod[bot] <174716857+elastic-renovate-prod[bot]@users.noreply.github.com>